### ISSUE TITLE
No backlit on navigation keys

### ISSUE THREAD

**Issue by Uvneshkumar** [TheScarastic/android_device_xiaomi_tissot#1]
Used all your trees, kernel and vendor to build RR for tissot. Everything was working fine except navigation keys were not backlit. What fix should I use?

**Comment by ghpranav** [comment]
This commit should fix it:
https://github.com/ghpranav/android_device_xiaomi_tissot/commit/400f3ef45856f57361d6c8914b10f2b4924b2ad5

**Comment by TheScarastic** [comment]
this isnt a place to ask help for rom building only report issues if bug appears in lineage :)
